apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-hostpath-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: torchbox.com/hostpath
parameters:
  pvDir: {{ .Values.path }}

