apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nfs.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "nfs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "nfs.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: {{ .Values.server }}
            - name: NFS_PATH
              value: {{ .Values.path }}
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{ .Values.server }}
            path: {{ .Values.path }}
      serviceAccount: {{ template "nfs.fullname" . }}

