global:
  host: my-k8s.att.io

  app:
    service:
      name: app
      port: 8080
  cache:
    service:
      name: cache
      port: 6379
  db:
    service:
      name: db
      port: 27017

app:
  persistent:
    enabled: false
    nfs:
      # FIXME: use the right IP
      server: 10.192.0.1
      path: /home/nesia/my-nfs
db:
  persistent:
    enabled: false
